### PR TITLE
CFE-926: Add functionality and embedded scripts for RFE-2052

### PR DESCRIPTION
**Pull request by lmzuccarelli**
This update implements the requirement for RF-2052. It uses a set of embedded scripts as outlined in the KCS article https://access.redhat.com/solutions/5343671

The scripts have been tested using the container specified by the Dockerfile.dev file

Example output

```
podman run --privileged --cap-add=NET_ADMIN -e NODE_IP=127.0.0.1 -e EXECUTE_SCRIPT=/tmp/scripts/metrics.sh -p 9000:9000 -it quay.io/<user-name>/node-observability-scripts:dev ./node-observability-agent --mode scripting --storage 
/tmp/results --loglevel debug
```

In a new terminal execute 

```
curl  -v http://127.0.0.1:9000/node-observability-scripting
```

Podman output 

```
WARN[0000] Error validating CNI config file /home/lzuccarelli/.config/cni/net.d/kind.conflist: [failed to find plugin "dnsname" in path [/usr/local/libexec/cni /usr/libexec/cni /usr/local/lib/cni /usr/lib/cni /opt/cni/bin]] 
INFO[0000] Starting node-observability-agent version: "v0.0.0-unknown", commit: "00801d1", build date: "2023-08-29T11:26:31Z", go version: "go1.19.10", GOOS: "linux", GOARCH: "amd64" at log level trace 
INFO[0000] Start listening on tcp://0.0.0.0:9000         module=server
INFO[0000] Targeting node 127.0.0.1                      module=server
INFO[0006] start handling status request                 module=handler
INFO[0006] agent is ready                                module=handler
INFO[0018] start handling status request                 module=handler
INFO[0018] previous profiling is still ongoing, runID: e669a8cb-b9b0-4f21-a57d-9a2228e8bc9b  module=handler
INFO[0025] Metrics collection completed                  module=handler
INFO[0025] successfully finished running Scripting - e669a8cb-b9b0-4f21-a57d-9a2228e8bc9b: 2023-09-08 10:55:41.63103853 +0000 UTC m=+15.849803234 -> 2023-09-08 10:55:51.726152976 +0000 UTC m=+25.944917673   module=handler

```

### CODE REVIEW

**Comment by lmzuccarelli** [comment]
I want to verify that the operator can trigger the agent with various scripts, this means some updates are needed in the operator and more than likely updates in the agent

**Review by sherine-k — APPROVED** [review]

**Pull request merged**
