### PR TITLE
CFE-250 - Fix linting issues

### PR DESCRIPTION
**Pull request by sherine-k**

### CODE REVIEW

**Review by lmzuccarelli — COMMENTED** [review]
@Sherine -  great now we are aligned on both the operator and agent

**Comment by lmzuccarelli** [comment]
@Sherine - question , the changes in the go code were they related to linting ?

**Comment by sherine-k** [comment]
> question , the changes in the go code were they related to linting ?

Yes, golint complains when any function or variable is public but not preceded by a comment... So I reviewed all the things in pkg/handlers that are not used outside that package, and made them private

**Comment by lmzuccarelli** [comment]
@Sherine - great thanks for the feeedback

**Pull request merged**
